const PDFDocument = require("pdfkit");
const { Order, OrderItem, Product, Customer, User, Collection } = require("../models");

exports.generateInvoicePdf = async (orderId) => {
  const order = await Order.findByPk(orderId, {
    include: [
      { model: Customer, as: "customer" },
      { model: User, as: "user", attributes: ["id", "name", "email"] },
      { model: OrderItem, as: "items", include: [{ model: Product, as: "product" }] },
      { model: Collection, as: "collections" },
    ],
  });

  if (!order) {
    const e = new Error("Order not found");
    e.status = 404;
    throw e;
  }

  const doc = new PDFDocument({ size: "A4", margin: 40 });

  // Header
  doc.fontSize(18).text("INVOICE", { align: "right" });
  doc.moveDown(0.5);
  doc.fontSize(10).text(`Order No: ${order.orderNumber}`, { align: "right" });
  doc.text(`Order Date: ${String(order.date).slice(0, 10)}`, { align: "right" });

  doc.moveDown(1);
  doc.fontSize(12).text("Customer", { underline: true });
  doc.fontSize(10).text(`${order.customer?.name || "-"}`);
  doc.text(`${order.customer?.phone || ""}`);
  doc.moveDown(1);

  // Items table
  doc.fontSize(12).text("Items", { underline: true });
  doc.moveDown(0.5);

  const startY = doc.y;
  doc.fontSize(10);
  doc.text("Product", 40, startY);
  doc.text("Qty", 280, startY, { width: 50, align: "right" });
  doc.text("Price", 340, startY, { width: 70, align: "right" });
  doc.text("Total", 420, startY, { width: 90, align: "right" });

  doc.moveDown(0.5);
  doc.moveTo(40, doc.y).lineTo(550, doc.y).stroke();

  let grand = 0;
  order.items?.forEach((it) => {
    const line = Number(it.total ?? (Number(it.price) * Number(it.quantity)));
    grand += line;

    doc.moveDown(0.5);
    doc.text(it.product?.name || it.productId, 40);
    doc.text(String(it.quantity), 280, doc.y - 10, { width: 50, align: "right" });
    doc.text(Number(it.price).toFixed(2), 340, doc.y - 10, { width: 70, align: "right" });
    doc.text(line.toFixed(2), 420, doc.y - 10, { width: 90, align: "right" });
  });

  doc.moveDown(1);
  doc.moveTo(40, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown(0.5);

  // Payments summary
  const approved = (order.collections || []).filter((c) => c.status === "APPROVED");
  const paid = approved.reduce((s, c) => s + Number(c.amount || 0), 0);
  const due = Math.max(0, Number(order.totalAmount || grand) - paid);

  doc.fontSize(11).text(`Order Total: ${Number(order.totalAmount || grand).toFixed(2)}`, { align: "right" });
  doc.text(`Paid (Approved): ${paid.toFixed(2)}`, { align: "right" });
  doc.text(`Balance Due: ${due.toFixed(2)}`, { align: "right" });

  doc.moveDown(1);
  doc.fontSize(9).fillColor("#555").text("Generated by ZForce System", { align: "center" });
  doc.fillColor("#000");

  return { doc, orderNumber: order.orderNumber };
};
