const PDFDocument = require("pdfkit");

const money = (n) => Number(n || 0).toFixed(2);

const drawKeyValue = (doc, x, y, key, value) => {
  doc.fontSize(9).fillColor("#374151").text(key, x, y);
  doc.fontSize(10).fillColor("#111827").text(value ?? "-", x + 140, y);
};

const hr = (doc, y) => {
  doc.moveTo(40, y).lineTo(555, y).strokeColor("#E5E7EB").stroke();
};

exports.createInvoicePdf = ({ order, company }) => {
  const doc = new PDFDocument({ size: "A4", margin: 40 });
  doc.info.Title = `Invoice ${order.orderNumber || order.id}`;

  // Header
  doc.fontSize(18).fillColor("#111827").text(company?.name || "Company", { align: "left" });
  doc.fontSize(9).fillColor("#6B7280").text(company?.address || "");
  if (company?.contactNo) doc.text(`Phone: ${company.contactNo}`);
  if (company?.email) doc.text(`Email: ${company.email}`);
  if (company?.binNo) doc.text(`BIN: ${company.binNo}`);
  if (company?.tiinNo) doc.text(`TIN: ${company.tiinNo}`);

  doc.moveDown(1);
  hr(doc, doc.y);
  doc.moveDown(1);

  // Invoice meta
  doc.fontSize(16).fillColor("#111827").text("INVOICE", { align: "right" });
  doc.moveDown(0.5);

  const topY = doc.y;
  drawKeyValue(doc, 40, topY, "Invoice No", order.orderNumber || "-");
  drawKeyValue(doc, 40, topY + 16, "Order Date", order.date || "-");
  drawKeyValue(doc, 40, topY + 32, "Status", order.status || "-");

  drawKeyValue(doc, 320, topY, "Customer", order.customer?.name || "-");
  drawKeyValue(doc, 320, topY + 16, "Phone", order.customer?.phone || "-");
  drawKeyValue(doc, 320, topY + 32, "Sales By", order.user?.name || "-");

  doc.moveDown(3);
  hr(doc, doc.y);
  doc.moveDown(1);

  // Items table header
  const tableTop = doc.y;
  doc.fontSize(10).fillColor("#111827");
  doc.text("#", 40, tableTop);
  doc.text("Product", 65, tableTop);
  doc.text("Qty", 320, tableTop, { width: 50, align: "right" });
  doc.text("Price", 380, tableTop, { width: 70, align: "right" });
  doc.text("Total", 460, tableTop, { width: 90, align: "right" });

  doc.moveDown(0.5);
  hr(doc, doc.y);
  doc.moveDown(0.5);

  // Items rows
  let i = 1;
  let y = doc.y;

  const items = order.items || [];
  items.forEach((it) => {
    const name = it.product?.name || "-";
    const qty = it.quantity;
    const price = it.price;
    const total = it.total;

    doc.fontSize(9).fillColor("#111827").text(String(i), 40, y);
    doc.text(name, 65, y, { width: 240 });
    doc.text(String(qty), 320, y, { width: 50, align: "right" });
    doc.text(money(price), 380, y, { width: 70, align: "right" });
    doc.text(money(total), 460, y, { width: 90, align: "right" });

    y += 18;

    // page break protection
    if (y > 740) {
      doc.addPage();
      y = 40;
    }

    i += 1;
  });

  doc.moveDown(2);
  hr(doc, doc.y);
  doc.moveDown(1);

  // Totals
  const totalAmount = Number(order.totalAmount || 0);
  const paidAmount = Number(order.paidAmount || 0);
  const dueAmount = Math.max(totalAmount - paidAmount, 0);

  const rightX = 360;
  const baseY = doc.y;

  doc.fontSize(10).fillColor("#111827");
  doc.text("Total Amount:", rightX, baseY, { width: 120, align: "right" });
  doc.text(money(totalAmount), rightX + 130, baseY, { width: 90, align: "right" });

  doc.text("Paid Amount:", rightX, baseY + 16, { width: 120, align: "right" });
  doc.text(money(paidAmount), rightX + 130, baseY + 16, { width: 90, align: "right" });

  doc.fontSize(11).fillColor("#111827");
  doc.text("Due Amount:", rightX, baseY + 34, { width: 120, align: "right" });
  doc.text(money(dueAmount), rightX + 130, baseY + 34, { width: 90, align: "right" });

  doc.moveDown(2);

  // Notes
  if (order.notes) {
    doc.fontSize(9).fillColor("#6B7280").text("Notes:", 40, doc.y);
    doc.fontSize(9).fillColor("#111827").text(order.notes, { width: 520 });
  }

  // Footer
  doc.moveDown(2);
  hr(doc, doc.y);
  doc.fontSize(8).fillColor("#6B7280").text("Generated by ZForce System", 40, doc.y + 6);

  return doc;
};

exports.createReceiptPdf = ({ collection, order, company }) => {
  const doc = new PDFDocument({ size: "A4", margin: 40 });
  doc.info.Title = `Receipt ${collection.id}`;

  // Header
  doc.fontSize(18).fillColor("#111827").text(company?.name || "Company");
  doc.fontSize(9).fillColor("#6B7280").text(company?.address || "");
  doc.moveDown(1);
  hr(doc, doc.y);
  doc.moveDown(1);

  doc.fontSize(16).fillColor("#111827").text("PAYMENT RECEIPT", { align: "right" });
  doc.moveDown(0.5);

  const topY = doc.y;

  drawKeyValue(doc, 40, topY, "Receipt No", String(collection.id).slice(0, 8) + "...");
  drawKeyValue(doc, 40, topY + 16, "Collected At", collection.collectedAt ? new Date(collection.collectedAt).toLocaleString() : "-");
  drawKeyValue(doc, 40, topY + 32, "Payment Type", collection.paymentType || "-");
  drawKeyValue(doc, 40, topY + 48, "Status", collection.status || "-");

  drawKeyValue(doc, 320, topY, "Customer", order.customer?.name || "-");
  drawKeyValue(doc, 320, topY + 16, "Phone", order.customer?.phone || "-");
  drawKeyValue(doc, 320, topY + 32, "Order No", order.orderNumber || "-");

  doc.moveDown(4);
  hr(doc, doc.y);
  doc.moveDown(1);

  const totalAmount = Number(order.totalAmount || 0);
  const paidAmount = Number(order.paidAmount || 0);
  const dueAmount = Math.max(totalAmount - paidAmount, 0);
  const received = Number(collection.amount || 0);

  doc.fontSize(12).fillColor("#111827").text(`Received Amount: ${money(received)} BDT`, { align: "left" });
  doc.moveDown(1);

  doc.fontSize(10).fillColor("#111827");
  doc.text(`Order Total: ${money(totalAmount)} BDT`);
  doc.text(`Total Paid (after approval): ${money(paidAmount)} BDT`);
  doc.text(`Remaining Due: ${money(dueAmount)} BDT`);

  doc.moveDown(2);
  hr(doc, doc.y);
  doc.fontSize(8).fillColor("#6B7280").text("This receipt is system generated.", 40, doc.y + 6);

  return doc;
};



// -------------------- Reports PDFs --------------------
const safe = (v) => (v === null || v === undefined || String(v).trim() === "" ? "-" : String(v));
const fmtDate = (v) => (v ? String(v).slice(0, 10) : "-");

const drawFiltersBlock = (doc, filters, x, y) => {
  doc.fontSize(9).fillColor("#6B7280").text("Filters", x, y);
  doc.fontSize(9).fillColor("#111827");

  const lines = [];
  const keys = [
    ["from", "From"],
    ["to", "To"],
    ["status", "Status"],
    ["paymentStatus", "Payment"],
    ["companyId", "CompanyId"],
    ["userId", "UserId"],
    ["customerId", "CustomerId"],
    ["region", "Region"],
    ["area", "Area"],
    ["territory", "Territory"],
    ["parentId", "ParentId"],
    ["role", "Role"],
    ["q", "Search"],
  ];

  keys.forEach(([k, label]) => {
    if (filters && filters[k]) lines.push(`${label}: ${filters[k]}`);
  });

  if (!lines.length) lines.push("No filters applied");

  doc.text(lines.join("   |   "), x, y + 14, { width: 515 });
};

exports.createSalesReportPdf = ({ rows = [], totals = {}, company = null, filters = {} }) => {
  const doc = new PDFDocument({ size: "A4", margin: 40 });
  doc.info.Title = "Sales Report";

  doc.fontSize(18).fillColor("#111827").text(company?.name || "ZForce - Sales Report");
  doc.fontSize(9).fillColor("#6B7280").text(company?.address || "");
  doc.moveDown(0.5);
  hr(doc, doc.y);
  doc.moveDown(0.8);

  drawFiltersBlock(doc, filters, 40, doc.y);
  doc.moveDown(2);
  hr(doc, doc.y);
  doc.moveDown(1);

  const tOrders = Number(totals.totalOrders || 0);
  const tSales = Number(totals.totalSales || 0);
  const tCollected = Number(totals.totalCollected || 0);
  const tDue = Number(totals.totalDue || 0);

  doc.fontSize(10).fillColor("#111827").text(`Total Orders: ${tOrders}`);
  doc.text(`Total Sales: ${money(tSales)}   |   Total Collected: ${money(tCollected)}   |   Total Due: ${money(tDue)}`);
  doc.moveDown(0.8);
  hr(doc, doc.y);
  doc.moveDown(1);

  let y = doc.y;
  doc.fontSize(9).fillColor("#111827");
  doc.text("Order", 40, y, { width: 80 });
  doc.text("Date", 120, y, { width: 70 });
  doc.text("User", 195, y, { width: 110 });
  doc.text("Customer", 310, y, { width: 140 });
  doc.text("Total", 455, y, { width: 60, align: "right" });
  doc.text("Paid", 520, y, { width: 60, align: "right" });

  doc.moveDown(0.5);
  hr(doc, doc.y);
  y = doc.y + 6;

  const ensureRoom = () => {
    if (y > 760) {
      doc.addPage();
      y = 40;
    }
  };

  rows.forEach((o) => {
    ensureRoom();
    doc.fontSize(8).fillColor("#111827");
    doc.text(safe(o.orderNumber || o.id), 40, y, { width: 80 });
    doc.text(fmtDate(o.date), 120, y, { width: 70 });
    doc.text(safe(o.user?.name), 195, y, { width: 110 });
    doc.text(safe(o.customer?.name), 310, y, { width: 140 });
    doc.text(money(o.totalAmount), 455, y, { width: 60, align: "right" });
    doc.text(money(o.paidAmount), 520, y, { width: 60, align: "right" });
    y += 16;
  });

  doc.moveDown(1.5);
  hr(doc, doc.y);
  doc.fontSize(8).fillColor("#6B7280").text("Generated by ZForce System", 40, doc.y + 6);

  return doc;
};

exports.createPerformanceReportPdf = ({ rows = [], company = null, filters = {} }) => {
  const doc = new PDFDocument({ size: "A4", margin: 40 });
  doc.info.Title = "Performance Report";

  doc.fontSize(18).fillColor("#111827").text(company?.name || "ZForce - Performance Report");
  doc.fontSize(9).fillColor("#6B7280").text(company?.address || "");
  doc.moveDown(0.5);
  hr(doc, doc.y);
  doc.moveDown(0.8);

  drawFiltersBlock(doc, filters, 40, doc.y);
  doc.moveDown(2);
  hr(doc, doc.y);
  doc.moveDown(1);

  let y = doc.y;
  doc.fontSize(9).fillColor("#111827");
  doc.text("User", 40, y, { width: 220 });
  doc.text("Orders", 270, y, { width: 70, align: "right" });
  doc.text("Sales", 350, y, { width: 90, align: "right" });
  doc.text("Avg", 450, y, { width: 70, align: "right" });
  doc.text("Max", 520, y, { width: 60, align: "right" });

  doc.moveDown(0.5);
  hr(doc, doc.y);
  y = doc.y + 6;

  const ensureRoom = () => {
    if (y > 760) {
      doc.addPage();
      y = 40;
    }
  };

  rows.forEach((r) => {
    ensureRoom();
    doc.fontSize(8).fillColor("#111827");
    doc.text(safe(r.userName), 40, y, { width: 220 });
    doc.text(String(r.totalOrders || 0), 270, y, { width: 70, align: "right" });
    doc.text(money(r.totalSales), 350, y, { width: 90, align: "right" });
    doc.text(money(r.avgOrderValue), 450, y, { width: 70, align: "right" });
    doc.text(money(r.maxOrderValue), 520, y, { width: 60, align: "right" });
    y += 16;
  });

  doc.moveDown(1.5);
  hr(doc, doc.y);
  doc.fontSize(8).fillColor("#6B7280").text("Generated by ZForce System", 40, doc.y + 6);

  return doc;
};
